sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HVN5Ctn9EeRmcW3kzsZew0IDtdSe39AV6Q9IABxgBMsLBc0Gz6Ab3NZjcrge31Gvt9He+92knVcTZ5pcA2V+tnFC1n2zzIzgQ3azRTDFkmJRVME/qw1At/JyaWdk8OXn2GnuX0MI+LxwiBRBEVJn2pPa4RHOnK70yUA4hk3imDU6n/5tshmZjbH+6EaFO+b2JEsdsQ0y4E1SlaVL7fSHjlphPCwGD3ULpygbpmbzvO1aFTkmk5Y0xqhRGfIndLo6oRZonCW3AnKfzs8aYftMSZs2qb0SV75du0D8/kqdl+oSu9giLW1OeJ3TFhX5E7nqqgEWFbMsoZ02C9aqDtpx4bwPIVF6SiFWNnGVrQ35yrnRjqmiSokoL19h47295kPoJyluP7RQfL/QY/usUVL/WOz4f04dLuZ7M35ySBPpg5Oi6/ee/XaTCmfErNVLdY7W2FnqhzHLAyH4wl3oiaZcQ91JrQTFVoza1H1SJfYEl8/mbXbX2f/NXum1Jmr7m43Rw7M6ZKxwNpSHWd4+cR6SDDzYIadjW1k0Oq0Ppbc4oDtTPE44jIZnjhlsWF0Ik5FJ7e3HFGwar38rptrHvUlGOPe3Ep7vYv0DSKur7jTjvvfEpLqGnsR5bvtk3ZW/7O9Xg9IedgU9IE9xP3yZ8NDwBAELhxgxlLS75qBCbAqaO/o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Romische-Geschichte-Band-8_3065
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy